dependencies {
	compileInclude group: "com.damnhandy", name: "handy-uri-templates", version: "2.1.8"
	compileInclude group: "com.fasterxml.jackson.core", name: "jackson-annotations", version: "2.18.2"
	compileInclude group: "com.fasterxml.jackson.core", name: "jackson-core", version: "2.18.2"
	compileInclude group: "com.fasterxml.jackson.core", name: "jackson-databind", version: "2.18.2"
	compileInclude group: "commons-codec", name: "commons-codec", version: "1.15"
	compileInclude group: "joda-time", name: "joda-time", version: "2.12.1"
	compileInclude group: "org.apache.commons", name: "commons-lang3", version: "3.18.0"
	compileInclude group: "org.apache.httpcomponents.client5", name: "httpclient5", version: "5.3.1"
	compileInclude group: "org.apache.httpcomponents.core5", name: "httpcore5", version: "5.3.1"
	compileInclude group: "org.apache.httpcomponents.core5", name: "httpcore5-h2", version: "5.3.1"
	compileInclude group: "org.joda", name: "joda-convert", version: "2.2.1"
	compileInclude group: "io.micrometer", name: "micrometer-commons", version: "1.14.5"
	compileInclude group: "io.micrometer", name: "micrometer-observation", version: "1.14.5"
	compileInclude group: "org.springframework", name: "spring-beans", version: "6.2.6"
	compileInclude group: "org.springframework", name: "spring-context", version: "6.2.6"
	compileInclude group: "org.springframework", name: "spring-core", version: "6.2.6"
	compileInclude group: "org.springframework", name: "spring-web", version: "6.2.6"
	compileInclude group: "org.springframework.hateoas", name: "spring-hateoas", version: "2.3.0"
	compileOnly group: "com.liferay.portal", name: "com.liferay.portal.kernel", version: "default"
	compileOnly group: "org.osgi", name: "org.osgi.service.component.annotations", version: "1.4.0"
	compileOnly project(":core:petra:petra-function")
	compileOnly project(":core:petra:petra-string")
	compileOnly project(":dxp:apps:osb:osb-faro:osb-faro-api")
	compileOnly project(":dxp:apps:osb:osb-faro:osb-faro-contacts-api")
}