<definition>
	<command name="addSelection">
		<default>
			<execute function="Portal.AddSelection#addSelection" />
		</default>
	</command>

	<command name="antCommand">
		<default>
			<execute function="Portal.AntCommand#antCommand" />
		</default>
	</command>

	<command name="assertAlertNotPresent">
		<default>
			<description message="Fail if the alert is present." />

			<execute function="Portal.AssertAlertNotPresent#assertAlertNotPresent" />
		</default>
	</command>

	<command name="assertChecked">
		<default>
			<execute function="Portal.AssertChecked#assertChecked" />
		</default>
	</command>

	<command name="assertClick">
		<case comparator="contains" locator1="/input">
			<execute function="Portal.AssertClick#assertValueClickAt" />
		</case>

		<default>
			<description message="Click on the ${locator1} with the value ${value1}." />

			<execute function="Portal.AssertClick#assertTextClickAt" />
		</default>
	</command>

	<command name="assertClickNoError">
		<case comparator="contains" locator1="/input">
			<execute function="Portal.AssertClickNoError#assertValueClick" />
		</case>

		<default>
			<description message="Click on the ${locator1} with the value ${value1}." />

			<execute function="Portal.AssertClickNoError#assertTextClick" />
		</default>
	</command>

	<command name="assertConsoleTextNotPresent">
		<default>
			<description message="Assert that the text ${value1} is NOT present within the console output." />

			<execute function="Portal.AssertConsoleTextNotPresent#assertConsoleTextNotPresent" />
		</default>
	</command>

	<command name="assertConsoleTextPresent">
		<default>
			<description message="Assert that the text ${value1} is present within the console output." />

			<execute function="Portal.AssertConsoleTextPresent#assertConsoleTextPresent" />
		</default>
	</command>

	<command name="assertElementNotPresent">
		<default>
			<description message="Assert that the ${locator1} is NOT present." />

			<execute function="Portal.AssertElementNotPresent#assertElementNotPresent" />
		</default>
	</command>

	<command name="assertElementPresent">
		<default>
			<description message="Assert that the ${locator1} is present." />

			<execute function="Portal.AssertElementPresent#assertVisible" />
		</default>
	</command>

	<command name="assertHTMLSourceTextNotPresent">
		<default>
			<execute function="Portal.AssertHTMLSourceTextNotPresent#assertHTMLSourceTextNotPresent" />
		</default>
	</command>

	<command name="assertHTMLSourceTextPresent">
		<default>
			<execute function="Portal.AssertHTMLSourceTextPresent#assertHTMLSourceTextPresent" />
		</default>
	</command>

	<command name="assertLocation">
		<default>
			<execute function="Portal.AssertLocation#assertLocation" />
		</default>
	</command>

	<command name="assertNotChecked">
		<default>
			<execute function="Portal.AssertNotChecked#assertNotChecked" />
		</default>
	</command>

	<command name="assertNotVisible">
		<default>
			<description message="Assert that the ${locator1} is NOT visible." />

			<execute function="Portal.AssertNotVisible#assertNotVisible" />
		</default>
	</command>

	<command name="assertSelectedLabel">
		<default>
			<execute function="Portal.AssertSelectedLabel#assertSelectedLabel" />
		</default>
	</command>

	<command name="assertTextEquals">
		<case comparator="contains" locator1="/input">
			<execute function="Portal.AssertTextEquals#assertValue" />
		</case>

		<default>
			<description message="Assert that the text at the ${locator1} is ${value1}." />

			<execute function="Portal.AssertTextEquals#assertText" />
		</default>
	</command>

	<command name="assertTextNotEquals">
		<case comparator="contains" locator1="/input">
			<execute function="Portal.AssertTextNotEquals#assertNotValue" />
		</case>

		<default>
			<description message="Assert that the text at the ${locator1} is NOT ${value1}." />

			<execute function="Portal.AssertTextNotEquals#assertNotText" />
		</default>
	</command>

	<command name="assertTextNotPresent">
		<default>
			<description message="Assert that the text ${value1} is NOT present." />

			<execute function="Portal.AssertTextNotPresent#assertTextNotPresent" />
		</default>
	</command>

	<command name="assertTextPresent">
		<default>
			<description message="Assert that the text ${value1} is present." />

			<execute function="Portal.AssertTextPresent#assertTextPresent" />
		</default>
	</command>

	<command name="assertValue">
		<default>
			<execute function="Portal.AssertValue#assertValue" />
		</default>
	</command>

	<command name="assertVisible">
		<default>
			<description message="Assert that the ${locator1} is visible." />

			<execute function="Portal.AssertVisible#assertVisible" />
		</default>
	</command>

	<command name="check">
		<default>
			<execute function="Portal.Check#clickAt" />
		</default>
	</command>

	<command name="click">
		<default>
			<description message="Click on the ${locator1}." />

			<execute function="Portal.Click#clickAt" />
		</default>
	</command>

	<command name="clickNoError">
		<default>
			<description message="Click on the ${locator1}." />

			<execute function="Portal.ClickNoError#click" />
		</default>
	</command>

	<command name="close">
		<default>
			<execute function="Portal.Close#close" />
		</default>
	</command>

	<command name="confirm">
		<default>
			<description message="Assert confirmation window has the value ${value1}." />

			<execute function="Portal.Confirm#assertConfirmation" />
		</default>
	</command>

	<command name="copy">
		<case comparator="contains" locator1="/input">
			<execute function="Portal.Copy#valueCopy" />
		</case>

		<default>
			<execute function="Portal.Copy#textCopy" />
		</default>
	</command>

	<command name="doubleClick">
		<default>
			<execute function="Portal.DoubleClick#doubleClickAt" />
		</default>
	</command>

	<command name="downloadTempFile">
		<default>
			<execute function="Portal.DownloadTempFile#downloadTempFile" />
		</default>
	</command>

	<command name="dragAndDrop">
		<default>
			<execute function="Portal.DragAndDrop#dragAndDropToObject" />
		</default>
	</command>

	<command name="isElementNotPresent">
		<default>
			<execute function="Portal.IsElementNotPresent#isElementNotPresent" />
		</default>
	</command>

	<command name="isElementPresent">
		<default>
			<execute function="Portal.IsElementPresent#isElementPresent" />
		</default>
	</command>

	<command name="isHTMLSourceTextPresent">
		<default>
			<execute function="Portal.IsHTMLSourceTextPresent#isHTMLSourceTextPresent" />
		</default>
	</command>

	<command name="isNotVisible">
		<default>
			<execute function="Portal.IsNotVisible#isNotVisible" />
		</default>
	</command>

	<command name="isTextEqual">
		<case comparator="contains" locator1="/input">
			<execute function="Portal.IsTextEqual#isValue" />
		</case>

		<default>
			<execute function="Portal.IsTextEqual#isText" />
		</default>
	</command>

	<command name="isTextNotEqual">
		<case comparator="contains" locator1="/input">
			<execute function="Portal.IsTextNotEqual#isNotValue" />
		</case>

		<default>
			<execute function="Portal.IsTextNotEqual#isNotText" />
		</default>
	</command>

	<command name="isVisible">
		<default>
			<execute function="Portal.IsVisible#isVisible" />
		</default>
	</command>

	<command name="keyPress">
		<default>
			<execute function="Portal.KeyPress#keyPress" />
		</default>
	</command>

	<command name="makeVisible">
		<default>
			<execute function="Portal.MakeVisible#makeVisible" />
		</default>
	</command>

	<command name="mouseDown">
		<default>
			<execute function="Portal.MouseDown#mouseDown" />
		</default>
	</command>

	<command name="mouseMove">
		<default>
			<execute function="Portal.MouseMove#mouseMove" />
		</default>
	</command>

	<command name="mouseOver">
		<default>
			<description message="Mouse over the ${locator1}." />

			<execute function="Portal.MouseOver#mouseOver" />
		</default>
	</command>

	<command name="mouseOverNoError">
		<default>
			<execute function="Portal.MouseOverNoError#mouseOverNoError" />
		</default>
	</command>

	<command name="mouseUp">
		<default>
			<execute function="Portal.MouseUp#mouseUp" />
		</default>
	</command>

	<command name="open">
		<default>
			<description message="Open the browser to the URL ${locator1}." />

			<execute function="Portal.Open#open" />
		</default>
	</command>

	<command name="paste">
		<default>
			<execute function="Portal.Paste#paste" />
		</default>
	</command>

	<command name="pause">
		<default>
			<execute function="Portal.Pause#pause" />
		</default>
	</command>

	<command name="refresh">
		<default>
			<execute function="Portal.Refresh#refresh" />
		</default>
	</command>

	<command name="scrollWebElementIntoView">
		<default>
			<execute function="Portal.ScrollWebElementIntoView#scrollWebElementIntoView" />
		</default>
	</command>

	<command name="select">
		<default>
			<execute function="Portal.Select#select" />
		</default>
	</command>

	<command name="selectFrame">
		<case comparator="contains" locator1="/iframe">
			<execute function="Portal.SelectFrame#selectFrame" />
		</case>

		<default>
			<execute function="Portal.SelectFrame#selectFrameTop" />
		</default>
	</command>

	<command name="selectFrameTop">
		<default>
			<execute function="Portal.SelectFrameTop#selectFrameTop" />
		</default>
	</command>

	<command name="selectNoError">
		<default>
			<execute function="Portal.SelectNoError#select" />
		</default>
	</command>

	<command name="selectWindow">
		<default>
			<execute function="Portal.SelectWindow#selectWindow" />
		</default>
	</command>

	<command name="setWindowSize">
		<default>
			<execute function="Portal.SetWindowSize#setWindowSize" />
		</default>
	</command>

	<command name="sikuliAssertElementNotPresent">
		<default>
			<execute function="Portal.SikuliAssertElementNotPresent#sikuliAssertElementNotPresent" />
		</default>
	</command>

	<command name="sikuliAssertElementPresent">
		<default>
			<execute function="Portal.SikuliAssertElementPresent#sikuliAssertElementPresent" />
		</default>
	</command>

	<command name="sikuliClick">
		<default>
			<description message="Click on the ${locator1}." />

			<execute function="Portal.SikuliClick#sikuliClick" />
		</default>
	</command>

	<command name="sikuliDragAndDrop">
		<default>
			<execute function="Portal.SikuliDragAndDrop#sikuliDragAndDrop" />
		</default>
	</command>

	<command name="sikuliLeftMouseDown">
		<default>
			<description message="Push left mouse button down." />

			<execute function="Portal.SikuliLeftMouseDown#sikuliLeftMouseDown" />
		</default>
	</command>

	<command name="sikuliLeftMouseUp">
		<default>
			<description message="Lift left mouse button up." />

			<execute function="Portal.SikuliLeftMouseUp#sikuliLeftMouseUp" />
		</default>
	</command>

	<command name="sikuliMouseMove">
		<default>
			<description message="Mouse over the ${locator1}." />

			<execute function="Portal.SikuliMouseMove#sikuliMouseMove" />
		</default>
	</command>

	<command name="sikuliRightMouseDown">
		<default>
			<description message="Push right mouse button down." />

			<execute function="Portal.SikuliRightMouseDown#sikuliRightMouseDown" />
		</default>
	</command>

	<command name="sikuliRightMouseUp">
		<default>
			<description message="Lift right mouse button up." />

			<execute function="Portal.SikuliRightMouseUp#sikuliRightMouseUp" />
		</default>
	</command>

	<command name="sikuliType">
		<default>
			<description message="Uses Sikuli to type into the ${locator1} with the value ${value1}." />

			<execute function="Portal.SikuliType#sikuliType" />
		</default>
	</command>

	<command name="sikuliUploadCommonFile">
		<default>
			<execute function="Portal.SikuliUploadCommonFile#sikuliUploadCommonFile" />
		</default>
	</command>

	<command name="sikuliUploadTCatFile">
		<default>
			<execute function="Portal.SikuliUploadTCatFile#sikuliUploadTCatFile" />
		</default>
	</command>

	<command name="sikuliUploadTempFile">
		<default>
			<execute function="Portal.SikuliUploadTempFile#sikuliUploadTempFile" />
		</default>
	</command>

	<command name="type">
		<default>
			<description message="Type into the ${locator1} with the value ${value1}." />

			<execute function="Portal.Type#type" />
		</default>
	</command>

	<command name="typeScreen">
		<default>
			<description message="Type the value ${value1}." />

			<execute function="Portal.TypeScreen#typeScreen" />
		</default>
	</command>

	<command name="uncheck">
		<default>
			<execute function="Portal.Uncheck#clickAt" />
		</default>
	</command>

	<command name="uploadCommonFile">
		<default>
			<execute function="Portal.UploadCommonFile#uploadCommonFile" />
		</default>
	</command>

	<command name="uploadFile">
		<default>
			<execute function="Portal.UploadFile#uploadFile" />
		</default>
	</command>

	<command name="uploadTempFile">
		<default>
			<execute function="Portal.UploadTempFile#uploadTempFile" />
		</default>
	</command>
</definition>