dependencies {
	compileOnly group: "com.liferay", name: "org.osgi.service.jaxrs", version: "1.0.0.JAKARTA-LIFERAY-PATCHED-1"
	compileOnly group: "com.liferay.portal", name: "release.dxp.api", version: "2026.q1.5"
	compileOnly group: "jakarta.annotation", name: "jakarta.annotation-api", version: "2.1.1"
	compileOnly project(":dxp:apps:osb:osb-faro:osb-faro-api")
	compileOnly project(":dxp:apps:osb:osb-faro:osb-faro-engine-client")
	compileOnly project(":dxp:apps:osb:osb-faro:osb-faro-rest-api")
}